(define (make-vect x y)
	(cons x y)
	)
(define (xcor-vert vert)
	(car vert))
(define (ycor-vert vert)
	(cdr vert))
(define (add-vert v1 v2)
	(make-vect (+ (xcor-vert v1) (xcor-vert v2)) (+ (ycor-vert v1) (ycor-vert v2))))
(define (sub-vert v1 v2)
	(make-vect (- (xcor-vert v1) (xcor-vert v2)) (- (ycor-vert v1) (ycor-vert v2))))
(define (scale-vert x vert)
	(make-vect (* x (xcor-vert v2)) (* x (ycor-vert v2))))