(define (time-prime-test n)
	(newline)
	(display n)
	(start-prime-test (real-time-clock))
)
(define (start-prime-test start-time)
	(report-prime (- (real-time-clock) start-time))
)
(define (report-prime elapsed-time)
	(display " *** ")
	(display elapsed-time)
)你·
(define (find-odd-prime product)
	(if
		(prime? product) 
		(time-prime-test product)
		(find-odd-prime (+ product 2))
	)
)